// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/bitrainforest/pulsar/internal/dao"
	"github.com/bitrainforest/pulsar/internal/service"
	"github.com/google/wire"
)

// Injectors from internal.go:

func NewServices() Services {
	userAppDao := dao.NewUserAppDao()
	userAppWatchDao := dao.NewUserAppWatchDao()
	userAppService := service.NewUserAppService(userAppDao, userAppWatchDao)
	services := Services{
		UserAppService: userAppService,
	}
	return services
}

// internal.go:

var Provider = wire.NewSet(dao.Provider, service.Provider, wire.Struct(new(Services), "*"))

type Services struct {
	UserAppService service.UserAppService
}
